{
 "title": "Generic Service",
 "description": "Simplifies monitoring services on Kubernetes. Shows container logs, availability, resource usage and HTTP and gRPC traffic.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{namespace=\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "loglevel",
    "label": "Log levels",
    "query": "trace,debug,info,warn,error,fatal"
   }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "description": "Logs reported by the main container (without sidecars)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\",container=\"$service\",level=~\"$loglevel\"}"
    },
    {
     "expr": "{namespace=\"$namespace\",container=\"$service\",level=\"\"}"
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Uptime",
   "type": "gauge",
   "description": "Average uptime of the service in the selected time range",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\nmin(ceil(kube_deployment_status_replicas_available{namespace=\"$namespace\",deployment=\"$service\"} \n    / kube_deployment_status_replicas{namespace=\"$namespace\",deployment=\"$service\"}))\n[$__range:1m])"
    }
   ]
  },
  {
   "title": "Replicas healthy",
   "type": "state-timeline",
   "description": "Timeline showing when how many of the desired replicas were healthy",
   "gridPos": { "h": 3, "w": 11, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas_available{namespace=\"$namespace\",deployment=~\"$service\"} / kube_deployment_status_replicas{namespace=\"$namespace\",deployment=~\"$service\"}) by (deployment)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "description": "Timeline showing when pod restarts occurred",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\",container=\"$service\"}[10m]))>0"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Memory usage of the main container (without sidecars)",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\",container=\"$service\",metrics_path=\"/metrics/cadvisor\"}",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{resource=\"memory\",namespace=\"$namespace\",container=\"$service\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\",container=\"$service\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage of the main container (without sidecars)",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"$service\",metrics_path=\"/metrics/cadvisor\"}[10m])",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"$namespace\",pod=~\"$service-.*\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$namespace\",pod=~\"$service-.*\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Status codes",
   "type": "timeseries",
   "description": "Request count by HTTP status code",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{destination_service_namespace=\"$namespace\",destination_service_name=\"$service\",reporter=\"source\",response_code=~\"2..\"}[10m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(istio_requests_total{destination_service_namespace=\"$namespace\",destination_service_name=\"$service\",reporter=\"source\",response_code=~\"3..\"}[10m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(istio_requests_total{destination_service_namespace=\"$namespace\",destination_service_name=\"$service\",reporter=\"source\",response_code=~\"4..\"}[10m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(istio_requests_total{destination_service_namespace=\"$namespace\",destination_service_name=\"$service\",reporter=\"destination\",response_code=~\"5..\"}[1h]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Response times",
   "type": "heatmap",
   "description": "Distribution of response times",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(istio_request_duration_milliseconds_bucket{destination_service_namespace=\"$namespace\",destination_service_name=\"$service\",reporter=\"source\"}[10m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Methods  + status codes",
   "type": "timeseries",
   "description": "Request count by gRPC method and status code",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{namespace=\"$namespace\",app=\"$service\",grpc_service!=\"grpc.health.v1.Health\",grpc_service!=\"grpc.reflection.v1alpha\",grpc_service!=\"/grpc.health.v1\",grpc_service!=\"/grpc.reflection.v1alpha.ServerReflection\"}[10m])) by (grpc_service, grpc_method, grpc_code)",
     "legendFormat": "{{ grpc_service }}/{{ grpc_method }} :: {{ grpc_code }}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "description": "Percentage of gRPC responses with status codes other than OK",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{namespace=\"$namespace\",app=\"$service\",grpc_code!=\"OK\",grpc_method!=\"Check\",grpc_method!=\"Watch\",grpc_method!=\"ServerReflectionInfo\"}[10m])) / sum(increase(grpc_server_handled_total{namespace=\"$namespace\",app=\"$service\",grpc_method!=\"Check\",grpc_method!=\"Watch\",grpc_method!=\"ServerReflectionInfo\"}[10m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Number of active Goroutines or threads in the thread pool",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\",app=\"$service\"}",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(coreclr_process_thread_count{namespace=\"$namespace\",service=\"$service\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Garbage collection",
   "type": "timeseries",
   "description": "Amount of time spent on garbage collection",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(go_gc_duration_seconds_sum{namespace=\"$namespace\",service=\"$service\"}[10m])",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "increase(coreclr_gc_collection_count{namespace=\"$namespace\",service=\"$service\"}[10m])",
     "legendFormat": "{{ pod }} ({{ generation }})"
    }
   ]
  }
 ]
}